[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.worker"

[deploy]
startCommand = "npx tsx pages/workers/wechat_verification_worker.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
